### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.22.dylib

### ISSUE THREAD

**Issue by kargeor** [osx-cross/homebrew-avr#200]
```
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.22.dylib
  Referenced from: /usr/local/Cellar/avr-gcc/9.3.0/libexec/gcc/avr/9.3.0/cc1
  Reason: image not found
avr-gcc: internal compiler error: Abort trap: 6 signal terminated program cc1
Please submit a full bug report,
with preprocessed source if appropriate.
```

**MacOS Big Sur 11.0.1 (20B28)**

**Comment by ladislas** [comment]
this should be fixed, can you `brew update` and `brew install avr-gcc` again?

**Comment by kargeor** [comment]
after doing that now I get:
```
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find crtatmega1284p.o: No such file or directory
/usr/local/opt/avr-binutils/bin/avr-ld: skipping incompatible /usr/local/Cellar/avr-gcc/9.3.0/lib/avr-gcc/9/gcc/avr/9.3.0/libgcc.a when searching for -lgcc
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find -lgcc
/usr/local/opt/avr-binutils/bin/avr-ld: skipping incompatible /usr/local/Cellar/avr-gcc/9.3.0/lib/avr-gcc/9/gcc/avr/9.3.0/../../../../../../avr/lib/libm.a when searching for -lm
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find -lm
/usr/local/opt/avr-binutils/bin/avr-ld: skipping incompatible /usr/local/Cellar/avr-gcc/9.3.0/lib/avr-gcc/9/gcc/avr/9.3.0/../../../../../../avr/lib/libc.a when searching for -lc
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find -lc
/usr/local/opt/avr-binutils/bin/avr-ld: cannot find -latmega1284p
```

**Comment by ladislas** [comment]
yes, everything is broken, see #204
will fix soon

**Comment by salkinium** [comment]
This is still broken with the [latest 10.2.0 bottle](https://github.com/modm-io/modm/runs/1691593998):

```
Compiling C++·· build/release/modm/src/modm/utils/dummy.o
scons: building terminated because of errors.dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.23.dylib
  Referenced from: /usr/local/Cellar/avr-gcc@10/10.2.0/libexec/gcc/avr/10.2.0/cc1plus
  Reason: image not found
avr-g++: internal compiler error: Abort trap: 6 signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/osx-cross/homebrew-avr/issues> for instructions.
scons: *** [build/release/modm/src/modm/utils/dummy.o] Error 4
```

Clean install in GitHub Actions macOS 10.15 CI, we also still get the issue in #205.
```
$ brew tap osx-cross/avr
$ export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 # To avoid this bullshit
$ brew install avr-gcc@10
$ echo "/usr/local/opt/avr-gcc@10/bin" >> $GITHUB_PATH
$ avr-g++ --version
avr-g++ (Homebrew AVR GCC 10.2.0) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ladislas** [comment]
I don't recommend using 10.2.0. 

Can you try with 9? 

Also can you build from source?

Have you tried brew update && brew upgrade?

What is the output of brew doctor?

**Comment by ladislas** [comment]
@salkinium I've just tested again, avr-gcc@10 works perfectly.

As said, try:

```
$ brew remove avr-gcc@10 # and all the other versions installed
$ brew cleanup -s
$ brew update && brew upgrade
$ brew cleanup -s
$ brew install avr-gcc@10 && brew link --force avr-gcc@10
```

If it still doesn't work, you can:

```
$ brew install --build-from-source avr-gcc@10
$ brew link --force avr-gcc@10
```

Please also try `avr-gcc` (v9.3.0).

Also, what is this?

> `$ export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 # To avoid this bullshit`

Finally, I don't understand this:

> `$ echo "/usr/local/opt/avr-gcc@10/bin" >> $GITHUB_PATH`

**Comment by kargeor** [comment]
`brew install avr-gcc@10 && brew link --force avr-gcc@10` worked for me (MacOS Big Sur 11.0.1). Thanks.

**Comment by salkinium** [comment]
I forgot to do `brew update` in our CI… 🤦‍♂️

This works fine now on the macOS 10.15 GitHub Actions CI, it also works fine locally on my 10.14 machine.
```
brew update
brew install avr-gcc@10
brew link --force avr-gcc@10
```

Thanks for your work!

**Comment by ladislas** [comment]
Good to hear!
